shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

packages:
  - 'packages/**'

catalogs:
  tooling:
    '@favorodera/eslint-config': ^1.0.4
    '@tsdown/css': ^0.22.14
    '@types/node': ^26.1.2
    '@vitest/ui': ^4.1.10
    eslint: ^10.8.0
    relizy: ^1.4.9
    tsdown: ^0.22.5
    turbo: ^2.10.7
    typescript: ^6.0.3
    vite: ^8.1.4
    vitest: ^4.1.10
    vue-tsc: ^3.3.7
  vendor:
    '@clack/prompts': ^1.7.0
    '@tailwindcss/vite': ^4.3.3
    '@vitejs/plugin-vue': ^6.0.7
    '@vueuse/core': ^14.4.0
    c12: 4.0.0-beta.5
    citty: ^0.2.2
    fs-extra: ^11.4.0
    nypm: ^0.6.9
    pathe: ^2.0.3
    reka-ui: ^2.10.1
    tailwind-merge: ^3.6.0
    tailwind-variants: ^3.3.0
    tailwindcss: ^4.3.3
    vue: ^3.5.39
nodeOptions: --max_old_space_size=4096

peerDependencyRules:
  allowedVersions:
    typescript: '6'
    vite: '8'
