/** Internal icon mappings */
export const iconsConfig = {
  caution: 'lucide:triangle-alert',
  check: 'lucide:check',
  chevronDown: 'lucide:chevron-down',
  chevronLeft: 'lucide:chevron-left',
  chevronRight: 'lucide:chevron-right',
  chevronUp: 'lucide:chevron-up',
  clipboard: 'lucide:clipboard',
  copy: 'lucide:copy',
  dark: 'lucide:moon',
  error: 'lucide:circle-x',
  external: 'lucide:arrow-up-right',
  file: 'lucide:file',
  folder: 'lucide:folder',
  folderOpen: 'lucide:folder-open',
  info: 'lucide:info',
  light: 'lucide:sun',
  menu: 'lucide:menu',
  panelClose: 'lucide:panel-left-close',
  panelOpen: 'lucide:panel-left-open',
  search: 'lucide:search',
  success: 'lucide:circle-check',
  system: 'lucide:monitor',
  tip: 'lucide:lightbulb',
  warning: 'lucide:triangle-alert',
  x: 'lucide:x',
}
