/** Internal icon mappings */
export const iconsConfig = {
  caution: 'tabler:alert-square-rounded',
  check: 'tabler:check',
  chevronDown: 'tabler:chevron-down',
  chevronLeft: 'tabler:chevron-left',
  chevronRight: 'tabler:chevron-right',
  chevronUp: 'tabler:chevron-up',
  clipboard: 'tabler:clipboard',
  copy: 'tabler:copy',
  dark: 'tabler:moon',
  error: 'tabler:circle-x',
  external: 'tabler:arrow-up-right',
  file: 'tabler:file',
  folder: 'tabler:folder',
  folderOpen: 'tabler:folder-open',
  info: 'tabler:info-square-rounded',
  light: 'tabler:sun',
  menu: 'tabler:menu',
  panelClose: 'tabler:layout-sidebar-left-collapse',
  panelOpen: 'tabler:layout-sidebar-left-expand',
  search: 'tabler:search',
  success: 'tabler:circle-check',
  system: 'tabler:device-desktop',
  tip: 'tabler:bulb',
  warning: 'tabler:alert-triangle',
  x: 'tabler:x',
}
